# GolangCI-Lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  
  # Skip directories
  skip-dirs:
    - vendor
    - bin
    - docs
    - .git
  
  # Skip files
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"  # Skip test files for some linters

linters:
  enable:
    # Enabled by default
    - errcheck      # Check error handling
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Unused code
    
    # Additional useful linters
    - gofmt         # Format code
    - goimports     # Manage imports
    - misspell      # Spell check
    - unconvert     # Remove unnecessary conversions
    - unparam       # Unused function parameters
    - gosec         # Security checks
    - bodyclose     # HTTP response body closed
    - noctx         # HTTP requests with context
    - exportloopref # Loop variable capture
    
  disable:
    - typecheck     # Too strict for skeleton code

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/gosouza/iac-ai-agent
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path from variable (needed for flexibility)
  
  misspell:
    locale: US
  
  unused:
    check-exported: false

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Exclude some linters from running on tests
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam
    
    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    - text: "Use of weak random number generator"
      linters:
        - gosec
    
    # Allow TODO comments
    - text: "Line contains TODO"
      linters:
        - godox
  
  # Show only new issues
  new: false
  
  # Fix found issues (if it's supported by the linter)
  fix: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true
  sort-results: true
