# Configuração do IaC AI Agent
# Agente inteligente com capacidades modulares para análise de Infrastructure as Code

# Informações básicas do agente
agent_id: "iac-ai-agent"
agent_name: "IaC AI Agent"
description: "Agente inteligente para análise de Infrastructure as Code"
version: "1.0.0"

# Configurações de logging
logging:
  level: "info"  # debug, info, warn, error
  file: "/var/log/iac-ai-agent.log"
  max_size: "100MB"
  max_backups: 3
  max_age: 28

# Configurações Web3
web3:
  wallet_address: "0x17eDfB8a794ec4f13190401EF7aF1c17f3cc90c5"
  nft_contract: "nation.fun"
  lit_protocol: true

# Configurações de billing
billing:
  enabled: true
  token_costs:
    analyze: 1
    security: 1
    cost: 1
    deep: 2
  free_commands:
    - "help"
    - "status"
    - "ping"
    - "health"

# Configurações das habilidades (capabilities)
capabilities:
  # Habilidade WhatsApp
  whatsapp:
    enabled: true
    webhook_url: "https://seu-dominio.com/webhook/whatsapp"
    
    # Configurações de rate limiting
    rate_limiting:
      enabled: true
      requests_per_hour: 100
      burst_size: 10
    
    # Configurações de segurança
    security:
      require_signature: true
      ip_whitelist: []
    
    # Configurações de retry
    retry:
      max_attempts: 3
      backoff_multiplier: 2
      max_backoff: "30s"

  # Habilidade de análise IaC
  iac-analysis:
    enabled: true
    
    # Analisadores habilitados
    terraform_enabled: true
    security_enabled: true
    cost_enabled: true
    
    # Provedores suportados
    providers:
      - "aws"
      - "azure"
      - "gcp"
      - "kubernetes"
    
    # Configurações de análise
    analysis:
      depth: "standard"  # quick, standard, deep
      timeout: "30s"
      max_file_size: "1MB"
      max_files: 10
    
    # Configurações de segurança
    security:
      checkov_enabled: true
      tfsec_enabled: true
      custom_rules: []
    
    # Configurações de custos
    cost:
      aws_pricing_enabled: true
      azure_pricing_enabled: true
      gcp_pricing_enabled: true
      currency: "USD"
    
    # Configurações de cache
    cache:
      enabled: true
      ttl: "1h"
      max_size: "100MB"

  # Habilidade Telegram (exemplo de extensibilidade)
  telegram:
    enabled: false
    bot_token: ""
    webhook_url: ""
    
  # Habilidade Slack (exemplo de extensibilidade)
  slack:
    enabled: false
    bot_token: ""
    signing_secret: ""

# Configurações de banco de dados
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  name: "iac_ai_agent"
  username: "iac_agent"
  password: "sua_senha_aqui"
  ssl_mode: "require"
  max_connections: 100
  connection_timeout: "30s"

# Configurações de cache
cache:
  enabled: true
  type: "redis"
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  ttl: "1h"
  max_memory: "100MB"

# Configurações de monitoramento
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"
  prometheus_enabled: true
  
  # Configurações de alertas
  alerts:
    enabled: true
    channels:
      - "email"
      - "slack"
    
    # Configurações de email
    email:
      smtp_host: "smtp.gmail.com"
      smtp_port: 587
      username: "seu-email@gmail.com"
      from: "iac-ai-agent@example.com"
      to: ["admin@example.com"]
    
    # Configurações de Slack
    slack:
      webhook_url: "https://hooks.slack.com/services/..."
      channel: "#alerts"

# Configurações de notificações
notifications:
  enabled: true
  
  # Configurações de webhook
  webhooks:
    enabled: true
    endpoints:
      - "https://example.com/webhook/iac-agent"
    
    # Configurações de retry
    retry:
      max_attempts: 3
      backoff_multiplier: 2
      max_backoff: "30s"

# Configurações de backup
backup:
  enabled: true
  schedule: "0 2 * * *"  # Diariamente às 2h
  retention_days: 30
  
  # Configurações de armazenamento
  storage:
    type: "s3"
    bucket: "iac-ai-agent-backups"
    region: "us-east-1"
    access_key: ""
    secret_key: ""

# Configurações de desenvolvimento
development:
  debug_mode: false
  mock_services: false
  test_data: false
  hot_reload: false
  
  # Configurações de profiling
  profiling:
    enabled: false
    port: 6060

# Configurações de produção
production:
  ssl_enabled: true
  ssl_cert: "/path/to/cert.pem"
  ssl_key: "/path/to/key.pem"
  
  # Configurações de CORS
  cors_enabled: true
  cors_origins:
    - "https://seu-dominio.com"
    - "https://app.seu-dominio.com"
  
  # Configurações de rate limiting global
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  
  # Configurações de timeout
  timeouts:
    read: "30s"
    write: "30s"
    idle: "60s"
