# Agent Templates Configuration
# ============================
# Define os templates de agentes disponíveis

templates:
  - id: general-purpose
    name: "General Purpose IaC Agent"
    description: "Agente versátil para análise completa de Infrastructure as Code"
    category: general
    is_recommended: true
    use_cases:
      - "Análise completa de Terraform"
      - "Review de Pull Requests"
      - "Detecção de problemas de segurança"
      - "Sugestões de otimização"
      - "Best practices"
    tags:
      - terraform
      - aws
      - azure
      - gcp
      - security
      - cost

  - id: security-specialist
    name: "Security Specialist Agent"
    description: "Agente especializado em análise de segurança e compliance"
    category: security
    is_recommended: false
    use_cases:
      - "Auditoria de segurança profunda"
      - "Compliance validation"
      - "Secrets detection"
      - "IAM policy review"
    tags:
      - security
      - compliance
      - checkov
      - secrets
      - iam

  - id: cost-optimizer
    name: "Cost Optimizer Agent"
    description: "Agente especializado em análise e otimização de custos"
    category: cost
    is_recommended: false
    use_cases:
      - "Análise de custos"
      - "Recomendações de economia"
      - "Resource rightsizing"
      - "Reserved instances"
    tags:
      - cost
      - optimization
      - savings
      - pricing

  - id: architecture-advisor
    name: "Architecture Advisor Agent"
    description: "Agente especializado em análise e sugestões arquiteturais"
    category: architecture
    is_recommended: false
    use_cases:
      - "Análise de padrões arquiteturais"
      - "Sugestões de design"
      - "Module recommendations"
      - "Code refactoring"
    tags:
      - architecture
      - patterns
      - best-practices
      - design

# Default Agent Configuration
# ===========================
# Configuração padrão para novos agentes

default_config:
  # LLM Configuration
  llm_provider: openai
  llm_model: gpt-4
  temperature: 0.2
  max_tokens: 4000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

  # Analysis Features
  enable_checkov: true
  enable_iam_analysis: true
  enable_cost_analysis: true
  enable_drift_detection: true
  enable_preview_analysis: true
  enable_secrets_scanning: true

  # Response Configuration
  response_format: json
  include_code_examples: true
  include_references: true
  detail_level: standard
  language: pt-br
  timezone: America/Sao_Paulo

# Default Capabilities
# ====================

default_capabilities:
  # Analysis
  can_analyze_terraform: true
  can_analyze_checkov: true
  can_analyze_iam: true
  can_analyze_costs: true
  can_detect_drift: true
  can_analyze_preview: true
  can_scan_secrets: true

  # Generation
  can_generate_code: true
  can_generate_tests: false
  can_generate_documentation: true
  can_refactor_code: true

  # Advisory
  can_suggest_architecture: true
  can_suggest_modules: true
  can_suggest_optimizations: true
  can_suggest_security: true

  # Integrations
  can_integrate_github: true
  can_integrate_ci: false
  can_integrate_slack: false
  can_integrate_discord: false

  # Learning
  can_learn_from_feedback: false
  can_adapt_to_context: true
  can_remember_preferences: false

# Default Personality
# ===================

default_personality:
  style: professional
  tone: encouraging
  verbosity: balanced
  use_emojis: true
  use_humor: false
  be_encouraging: true
  be_directive: false

  explain_reasoning: true
  provide_examples: true
  compare_alternatives: true
  highlight_risks: true

  ask_clarifying_questions: false
  offer_alternatives: true
  suggest_best_practices: true

# Default Knowledge
# =================

default_knowledge:
  # Expertise Levels
  terraform_expertise: expert
  aws_expertise: expert
  azure_expertise: intermediate
  gcp_expertise: intermediate
  security_expertise: expert
  networking_expertise: intermediate
  kubernetes_expertise: intermediate
  database_expertise: intermediate

  # Compliance & Industry
  compliance_frameworks:
    - GDPR
    - SOC2
    - HIPAA
    - PCI-DSS

  industry_focus:
    - general

  architecture_patterns:
    - 3-tier
    - microservices
    - serverless

  # Custom Rules (examples)
  custom_rules: []

  preferred_modules: []

  banned_resources: []

  required_tags:
    - Environment
    - Owner
    - ManagedBy

# Default Limits
# ==============

default_limits:
  # Rate Limits
  max_requests_per_hour: 100
  max_requests_per_day: 1000
  max_concurrent_requests: 5

  # Token Limits
  max_tokens_per_request: 4000
  max_tokens_per_day: 100000

  # Analysis Limits
  max_files_per_analysis: 50
  max_file_size_mb: 10
  max_resources_per_file: 200

  # Cost Limits (USD)
  max_cost_per_request: 0.50
  max_cost_per_day: 10.00
  max_cost_per_month: 200.00

  # Time Limits (seconds)
  max_analysis_time_seconds: 300
  request_timeout_seconds: 60
