# IaC AI Agent Configuration

# Server Configuration
server:
  port: "8080"
  host: "0.0.0.0"

# LLM Configuration
llm:
  provider: "openai"        # Provedor LLM (openai)
  model: "gpt-3.5-turbo"    # Modelo a ser usado
  temperature: 0.2          # Temperatura (0.0-1.0)
  max_tokens: 4000          # Máximo de tokens por resposta
  # api_key: ""             # Definir via env var LLM_API_KEY

# GitHub Configuration
github:
  # token: ""               # Definir via env var GITHUB_TOKEN
  # webhook_secret: ""      # Definir via env var GITHUB_WEBHOOK_SECRET
  auto_comment: true        # Comentar automaticamente em PRs

# Analysis Configuration
analysis:
  checkov_enabled: true           # Habilitar análise Checkov
  iam_analysis_enabled: true      # Habilitar análise IAM
  cost_optimization_enabled: true # Habilitar otimização de custos

# Scoring Configuration
scoring:
  min_pass_score: 70        # Score mínimo para aprovação (0-100)

# Logging Configuration
logging:
  level: "info"             # debug, info, warn, error
  format: "json"            # json, text

# Web3 Configuration
web3:
  # Privy Configuration
  privy_app_id: "cmgh6un8w007bl10ci0tgitwp"  # ID do aplicativo Privy.io
  privy_verification_key_url: "https://api.privy.io/v1/siwe/keys"

  # Base Network Configuration
  base_rpc_url: "https://goerli.base.org"  # Base Goerli Testnet
  base_chain_id: 84531                     # Base Goerli Chain ID

  # Smart Contract Addresses
  nft_access_contract_address: "0x123456789abcdef123456789abcdef12345678"  # Temporário até deploy
  bot_token_contract_address: "0x987654321abcdef987654321abcdef98765432"   # Temporário até deploy

  # Token Configuration
  token_symbol: "IACAI"
  token_decimals: 18

  # Features
  enable_nft_access: true
  enable_token_payments: true

  # Rate Limiting by Tier (requests per hour)
  basic_tier_rate_limit: 100
  pro_tier_rate_limit: 1000
  enterprise_tier_rate_limit: 10000
  
  # Nation.fun Configuration
  # wallet_token: ""        # Definir via env var WALLET_TOKEN
  # wallet_address: ""      # Definir via env var WALLET_ADDRESS
  default_agent_address: "0x147e832418Cc06A501047019E956714271098b89"  # Agente padrão Nation.fun