# IaC AI Agent Configuration

# Server Configuration
server:
  port: "8080"
  host: "0.0.0.0"

# LLM Configuration
llm:
  provider: "nation.fun"    # Provedor LLM (nation.fun)
  model: "nation-1"         # Modelo a ser usado
  temperature: 0.2          # Temperatura (0.0-1.0)
  max_tokens: 4000          # Máximo de tokens por resposta
  # api_key: ""             # Definir via env var LLM_API_KEY

# GitHub Configuration
github:
  # token: ""               # Definir via env var GITHUB_TOKEN
  # webhook_secret: ""      # Definir via env var GITHUB_WEBHOOK_SECRET
  auto_comment: true        # Comentar automaticamente em PRs

# Analysis Configuration
analysis:
  checkov_enabled: true           # Habilitar análise Checkov
  iam_analysis_enabled: true      # Habilitar análise IAM
  cost_optimization_enabled: true # Habilitar otimização de custos

# Scoring Configuration
scoring:
  min_pass_score: 70        # Score mínimo para aprovação (0-100)

# Logging Configuration
logging:
  level: "info"             # debug, info, warn, error
  format: "json"            # json, text

# Web3 Configuration
web3:
  # Privy Configuration
  privy_app_id: "cmgh6un8w007bl10ci0tgitwp"  # ID do aplicativo Privy.io
  privy_verification_key_url: "https://api.privy.io/v1/siwe/keys"

  # Base Network Configuration
  base_rpc_url: "https://goerli.base.org"  # Base Goerli Testnet
  base_chain_id: 84531                     # Base Goerli Chain ID

  # Smart Contract Addresses
  nft_access_contract_address: "0x147e832418Cc06A501047019E956714271098b89"  # NFT Contract Address
  # bot_token_contract_address: ""   # Definir via env var TOKEN_CONTRACT_ADDRESS

  # Token Configuration
  token_symbol: "IACAI"
  token_decimals: 18

  # Features
  enable_nft_access: true
  enable_token_payments: true

  # Rate Limiting by Tier (requests per hour)
  basic_tier_rate_limit: 100
  pro_tier_rate_limit: 1000
  enterprise_tier_rate_limit: 10000
  
  # Nation.fun Configuration
  # wallet_token: ""        # Definir via env var WALLET_TOKEN
  wallet_address: "0x17eDfB8a794ec4f13190401EF7aF1c17f3cc90c5"  # Wallet padrão autorizada
  default_agent_address: "0x147e832418Cc06A501047019E956714271098b89"  # Agente padrão Nation.fun
  
  # Nation NFT Validation Configuration
  nation_nft_required: true
  nation_nft_contract: "0x1234567890123456789012345678901234567890"  # Endereço do contrato NFT do Nation

# Notion Configuration
notion:
  # api_key: ""             # Definir via env var NOTION_API_KEY
  base_url: "https://api.notion.com/v1"  # URL base da API Notion
  
  # Agent Configuration
  agent_name: "IaC AI Agent"  # Nome do agente no Notion
  agent_description: "Intelligent Infrastructure as Code Analysis Agent"
  
  # Features
  enable_agent_creation: true    # Habilitar criação automática de agente
  auto_create_on_startup: true    # Criar agente automaticamente na inicialização
  
  # Rate Limiting
  max_requests_per_minute: 60     # Limite de requisições por minuto