# Configuração do Agente WhatsApp
# Este arquivo contém as configurações necessárias para o agente WhatsApp

# Informações básicas do agente
name: "IaC AI Agent WhatsApp"
description: "Agente para análise de infraestrutura via WhatsApp"

# Endereço da wallet Ethereum (deve possuir NFT Nation.fun)
wallet_address: "0x17eDfB8a794ec4f13190401EF7aF1c17f3cc90c5"

# Configurações do webhook WhatsApp
webhook_url: "https://seu-dominio.com/webhook/whatsapp"
verify_token: "seu_token_secreto_aqui"

# Configurações de logging
logging:
  level: "info"  # debug, info, warn, error
  file: "/var/log/whatsapp-agent.log"
  max_size: "100MB"
  max_backups: 3
  max_age: 28

# Configurações de rate limiting
rate_limiting:
  enabled: true
  requests_per_hour: 100
  burst_size: 10

# Configurações de billing
billing:
  enabled: true
  token_cost:
    analyze: 1
    security: 1
    cost: 1
  free_commands:
    - "help"
    - "status"
    - "balance"
    - "usage"

# Configurações de segurança
security:
  require_nft: true
  nft_contract: "nation.fun"
  signature_validation: true
  ip_whitelist: []

# Configurações de monitoramento
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"
  prometheus_enabled: true

# Configurações de notificações
notifications:
  enabled: true
  email:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "seu-email@gmail.com"
    password: "sua-senha-app"
  slack:
    webhook_url: "https://hooks.slack.com/services/..."
  discord:
    webhook_url: "https://discord.com/api/webhooks/..."

# Configurações de backup
backup:
  enabled: true
  schedule: "0 2 * * *"  # Diariamente às 2h
  retention_days: 30
  storage:
    type: "s3"
    bucket: "whatsapp-agent-backups"
    region: "us-east-1"

# Configurações de desenvolvimento
development:
  debug_mode: false
  mock_services: false
  test_data: false
  hot_reload: false

# Configurações de produção
production:
  ssl_enabled: true
  ssl_cert: "/path/to/cert.pem"
  ssl_key: "/path/to/key.pem"
  cors_enabled: true
  cors_origins:
    - "https://seu-dominio.com"
    - "https://app.seu-dominio.com"
