definitions:
  github_com_gosouza_iac-ai-agent_internal_models.AnalysisDetails:
    properties:
      cost:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.CostAnalysis'
      iam:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.IAMAnalysis'
      security:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.SecurityAnalysis'
      terraform:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.TerraformAnalysis'
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.AnalysisRequest:
    properties:
      branch:
        type: string
      commit_sha:
        type: string
      content:
        type: string
      path:
        type: string
      repository:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.AnalysisResponse:
    properties:
      analysis:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.AnalysisDetails'
      id:
        type: string
      metadata:
        additionalProperties: true
        type: object
      score:
        type: integer
      suggestions:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.Suggestion'
        type: array
      timestamp:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.Comment:
    properties:
      body:
        type: string
      line:
        type: integer
      path:
        type: string
      position:
        type: integer
      side:
        description: LEFT, RIGHT
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.CostAnalysis:
    properties:
      currency:
        type: string
      estimated_monthly_cost:
        type: number
      optimization_potential:
        type: number
      recommendations:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.CostRecommendation'
        type: array
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.CostRecommendation:
    properties:
      current_cost:
        type: number
      implementation_difficulty:
        description: easy, medium, hard
        type: string
      potential_savings:
        type: number
      recommendation:
        type: string
      resource:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.ErrorResponse:
    properties:
      code:
        type: string
      details:
        type: string
      error:
        type: string
      message:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.FileReview:
    properties:
      additions:
        type: integer
      changes:
        type: integer
      comments:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.Comment'
        type: array
      deletions:
        type: integer
      filename:
        type: string
      score:
        type: integer
      status:
        description: added, modified, deleted
        type: string
      suggestions:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.Suggestion'
        type: array
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.GraphEdge:
    properties:
      from:
        type: string
      to:
        type: string
      type:
        description: explicit, implicit
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.GraphNode:
    properties:
      id:
        type: string
      name:
        type: string
      resource:
        type: string
      type:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.IAMAnalysis:
    properties:
      admin_access_detected:
        type: boolean
      overly_permissive:
        type: boolean
      principal_risks:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.PrincipalRisk'
        type: array
      public_access:
        items:
          type: string
        type: array
      recommendations:
        items:
          type: string
        type: array
      total_policies:
        type: integer
      total_roles:
        type: integer
      wildcard_actions:
        items:
          type: string
        type: array
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.PrincipalRisk:
    properties:
      permissions:
        items:
          type: string
        type: array
      principal:
        type: string
      reason:
        type: string
      risk_level:
        type: string
      type:
        description: user, role, service
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.ResourceGraph:
    properties:
      edges:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.GraphEdge'
        type: array
      nodes:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.GraphNode'
        type: array
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.ReviewRequest:
    properties:
      installation_id:
        type: integer
      owner:
        type: string
      pr_number:
        type: integer
      repository:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.ReviewResponse:
    properties:
      analysis:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.AnalysisDetails'
      file_reviews:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.FileReview'
        type: array
      files_analyzed:
        type: integer
      id:
        type: string
      pr_number:
        type: integer
      repository:
        type: string
      score:
        type: integer
      status:
        description: approved, changes_requested, commented
        type: string
      summary:
        type: string
      timestamp:
        type: string
      total_suggestions:
        type: integer
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.SecurityAnalysis:
    properties:
      checks_failed:
        type: integer
      checks_passed:
        type: integer
      critical:
        type: integer
      findings:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.SecurityFinding'
        type: array
      high:
        type: integer
      info:
        type: integer
      low:
        type: integer
      medium:
        type: integer
      total_issues:
        type: integer
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.SecurityFinding:
    properties:
      check_id:
        type: string
      check_name:
        type: string
      description:
        type: string
      file:
        type: string
      guideline:
        type: string
      id:
        type: string
      line:
        type: integer
      references:
        items:
          type: string
        type: array
      resource:
        type: string
      severity:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.Suggestion:
    properties:
      auto_fix_available:
        type: boolean
      estimated_savings:
        type: string
      file:
        type: string
      line:
        type: integer
      message:
        type: string
      recommendation:
        type: string
      reference_link:
        type: string
      severity:
        description: critical, high, medium, low, info
        type: string
      type:
        description: security, cost, best_practice, performance
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.SyntaxError:
    properties:
      column:
        type: integer
      file:
        type: string
      line:
        type: integer
      message:
        type: string
      snippet:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.TerraformAnalysis:
    properties:
      best_practice_warnings:
        items:
          type: string
        type: array
      modules:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.TerraformModule'
        type: array
      outputs:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.TerraformOutput'
        type: array
      providers:
        items:
          type: string
        type: array
      resource_graph:
        $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ResourceGraph'
      resources:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.TerraformResource'
        type: array
      syntax_errors:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.SyntaxError'
        type: array
      total_data_sources:
        type: integer
      total_modules:
        type: integer
      total_outputs:
        type: integer
      total_resources:
        type: integer
      total_variables:
        type: integer
      valid:
        type: boolean
      variables:
        items:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.TerraformVariable'
        type: array
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.TerraformModule:
    properties:
      file:
        type: string
      inputs:
        additionalProperties: true
        type: object
      line_start:
        type: integer
      name:
        type: string
      source:
        type: string
      verified:
        type: boolean
      version:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.TerraformOutput:
    properties:
      description:
        type: string
      file:
        type: string
      name:
        type: string
      sensitive:
        type: boolean
      value:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.TerraformResource:
    properties:
      attributes:
        additionalProperties: true
        type: object
      dependencies:
        items:
          type: string
        type: array
      file:
        type: string
      line_end:
        type: integer
      line_start:
        type: integer
      name:
        type: string
      provider:
        type: string
      tags:
        additionalProperties:
          type: string
        type: object
      type:
        type: string
    type: object
  github_com_gosouza_iac-ai-agent_internal_models.TerraformVariable:
    properties:
      default: {}
      description:
        type: string
      file:
        type: string
      name:
        type: string
      required:
        type: boolean
      sensitive:
        type: boolean
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Retorna informações gerais sobre a API e seus endpoints disponíveis
      produces:
      - application/json
      responses:
        "200":
          description: Informações da API
          schema:
            additionalProperties: true
            type: object
      summary: Informações da API
      tags:
      - info
  /analyze:
    post:
      consumes:
      - application/json
      description: Analisa código Terraform para identificar problemas de segurança,
        custos e best practices
      parameters:
      - description: Requisição de análise
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.AnalysisRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Resultado da análise
          schema:
            $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.AnalysisResponse'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ErrorResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ErrorResponse'
      summary: Analisar código IaC
      tags:
      - analysis
  /health:
    get:
      description: Verifica o status de saúde do serviço
      produces:
      - application/json
      responses:
        "200":
          description: Status do serviço
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health
  /review:
    post:
      consumes:
      - application/json
      description: Executa uma análise completa de um Pull Request do GitHub
      parameters:
      - description: Requisição de review
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ReviewRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Resultado do review
          schema:
            $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ReviewResponse'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ErrorResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/github_com_gosouza_iac-ai-agent_internal_models.ErrorResponse'
      summary: Review de Pull Request
      tags:
      - review
swagger: "2.0"
